services:
  mailhaven-backend:
    build: ./backend
    container_name: mailhaven-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
      - JWT_SECRET=${JWT_SECRET}
      - DB_HOST=mailhaven-db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - MICROSOFT_CLIENT_ID=${MICROSOFT_CLIENT_ID}
      - MICROSOFT_TENANT_ID=${MICROSOFT_TENANT_ID}
      - MICROSOFT_CLIENT_SECRET=${MICROSOFT_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - OAUTH_REDIRECT_BASE_URL=${OAUTH_REDIRECT_BASE_URL}
    ports:
      - "3001:3001"
    networks:
      - mailhaven-net
    depends_on:
      - mailhaven-db
    volumes:
      - mailhaven-clamav-db:/var/lib/clamav
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
      - ./data:/app/data
      - ./check-update.sh:/root/mailhaven/check-update.sh
      - ./version.json:/app/version.json
      - ./CHANGELOG.md:/app/CHANGELOG.md

  mailhaven-frontend:
    build: ./frontend
    container_name: mailhaven-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - mailhaven-net
    depends_on:
      - mailhaven-backend

  mailhaven-db:
    image: postgres:17-alpine
    container_name: mailhaven-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - mailhaven-db-data:/var/lib/postgresql/data
      - ./backend/src/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mailhaven-net

networks:
  mailhaven-net:
    driver: bridge

volumes:
  mailhaven-db-data:
    external: true
    name: mailhaven_mailhaven-db-data
  mailhaven-clamav-db:
    external: true
    name: mailhaven_mailhaven-clamav-db
